### ISSUE TITLE
Update check issues

### ISSUE THREAD

**Issue by euchronicity** [CBLoader/CBLoader#5]
For some time the update check has failed on stock (but updated to current) Windows 10 and Windows 
7 PCs. I can see this when launching with -n -v switches:

```
D:\Apps\CBLoader>cbloader -n -v
CBLoader version 1.3.2b4
Debug: Working Directory is: C:\Program Files (x86)\Wizards of the Coast\Character Builder
Debug: Checking for merge and extract.
ERROR: Failed checking for Updates
Inner Exception: The underlying connection was closed: An unexpected error occurred on a send.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at CharacterBuilderLoader.Utils.CheckForNewVersion(String Version)
--------------------------------------------------------------------------------

Inner Exception:    Received an unexpected EOF or 0 bytes from the transport stream.
      at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
--------------------------------------------------------------------------------
```

 I believe this is because the default .NET System.Net.WebClient implementation for whichever .NET version CBLoader specifies (4.0? That's what my Powershell seems to use as well) doesn't use TLS 1.2 to do HTTPS (just SSL and TLS1.0). GitHub must've changed their settings at some point; most websites now only support TLS1.2 protocol.

One fix to this would be to explicitly add in the TLS1.2 protocol with something like this Powershell code

 [Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12

I don't have a .NET coding environment to build/verify the change, but in Powershell.

$wc = New-Object System.Net.WebClient
$version = $wc.DownloadString("https://github.com/CBLoader/CBLoader/raw/master/Releases/Current.txt")

fails with the exception

`Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."`

while 

$wc = New-Object System.Net.WebClient
[System.Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12
$version = $wc.DownloadString("https://github.com/CBLoader/CBLoader/raw/master/Releases/Current.txt")

works.

The change would have to be made to the CheckForNewVersion function in Utils.cs around line 176.

Anybody still able to make a new release?

**Comment by euchronicity** [comment]
I think this could also be fixed by recompiling targeting .NET version 4.6 or above, which use higher TLS by default?

**Comment by silasary** [comment]
The self-update feature has been removed for now.
